---
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: npm-install

- include: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
