---
- name: Remove firewalld Service
  service: name=firewalld state=stopped enabled=no
  when: iptables_service == 'false'

- name: Activate firewalld Service
  service: name=firewalld state=started enabled=yes
  when: iptables_service == 'true'

