---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Install nodejs.legacy
  apt: package=nodejs-legacy state=present update_cache=yes
  
- name: Add sudoers users to wheel group
  user: name=nodered groups=wheel append=yes state=present createhome=yes
  
- name: Install node-red for ubuntu
  shell: >
    npm install -g --unsafe-perm node-red
  become: yes
  become_user: nodered

- name: Install TheThingsNetwork Flow
  shell: <
    cd $HOME/.node-red
    npm install node-red-contrib-ttn
  become_user: nodered


#
#  npm:
#    name: node-red
#    production: yes
#    state: latest
    

