---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: Install nodejs.legacy
  apt: package=nodejs-legacy state=present update_cache=yes
  
- name: Add sudoers users to wheel group
  user: name=nodered groups=wheel append=yes state=present createhome=yes

- name: Install node-red for ubuntu
  become_user: nodered
  shell: >
    sudo npm install -g node-red
  notify: nodered installed

- name: Add systemctl service for node-red
  template:
    src: "node-red.service.j2"
    dest: "sudo nano /etc/systemd/system/node-red.service"
    owner: root
    group: root
    mode: 0644
  notify: nodered restart
  
- name: Install TheThingsNetwork Flow
  become_user: nodered
  shell: <
    cd /home/{{ nodeuser }}/.node-red
    sudo npm install node-red-contrib-ttn
  


#
#  npm:
#    name: node-red
#    production: yes
#    state: latest
    

