---
- hosts: all
  roles:
    - { role: common , tags: ["common"] }
    - { role: apache-reverse-proxy , tags: ["front"] }
    #- { role: letsencrypt , tags: ["ssl-cert"] }
    - { role: mosquitto, tags: ["mosquitto"] }
    - { role: npm, tags: ["npm"] }
    - { role: nodered, tags: ["nodered"] }
    #- { role: thingsboard , tags: ["dashboard"] }
