---
- name: Install NTP Ubuntu like
  apt: package=ntp state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install NTP EL like
  yum: name=ntp state=latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Copy over the NTP configuration
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntp

- name: ensure ntp is running
  service: name=ntp state=started
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: ensure ntp is running
  service: name=ntpd state=started
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Stop ntp Debian service
  service: name=ntp state=stopped
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Stop ntpd CentOS service
  service: name=ntpd state=stopped
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Checking correct date...
  shell: |
    ntpdate "{{ ntp_server }}"

- name: ensure ntp is running
  service: name=ntp state=started
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: ensure ntp is running
  service: name=ntpd state=started
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

